name: real-estate-app

services:
  demand-prediction:
    image: 957417441966.dkr.ecr.ap-south-1.amazonaws.com/real-estate-streamlit:latest
    container_name: real-estate
    env_file: .env

    ports:
      - "8000:8000"

    volumes:
      - /var/mlops/audit:/app/audit
